name: Build Docker Images

on:
  push:
    branches: ["main"]

env:
  REGISTRY: ghcr.io
  IMAGE_OWNER: ${{ github.repository_owner }}
  VERSION: 0.1.${{ github.run_number }}

jobs:
  build-docker:
    runs-on: python:3.11-alpine
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.IMAGE_OWNER }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build master image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/mcp-rewrite-proxy:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/mcp-rewrite-proxy:${{ env.VERSION }}
          build-args: |
            VERSION=${{ env.VERSION }}
          labels: |
            org.opencontainers.image.version=${{ env.VERSION }}
